// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSchedule.Data;

#nullable disable

namespace SchoolSchedule.Data.Migrations
{
    [DbContext(typeof(SchoolScheduleDbContext))]
    [Migration("20260901032554_FixClassSubjectGroupUniqueIndex")]
    partial class FixClassSubjectGroupUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SchoolSchedule.Core.Models.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ClassSubjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassId", "SubjectId")
                        .IsUnique()
                        .HasFilter("\"GroupLabel\" IS NULL");

                    b.HasIndex("ClassId", "SubjectId", "GroupLabel")
                        .IsUnique()
                        .HasFilter("\"GroupLabel\" IS NOT NULL");

                    b.ToTable("ClassSubjectGroups");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ScheduleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSecondShift")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodsPerDayShift1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodsPerDayShift2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduleSettings");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ScheduledLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassSubjectGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassSubjectGroupId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("ScheduledLessons");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeRoomId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredRoomType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Substitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledLessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubstituteRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubstituteTeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubstituteRoomId");

                    b.HasIndex("SubstituteTeacherId");

                    b.HasIndex("ScheduledLessonId", "Date")
                        .IsUnique();

                    b.ToTable("Substitutions");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLessonsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.TeacherUnavailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherUnavailabilities");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Shift", "Day", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Absence", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.Teacher", "Teacher")
                        .WithMany("Absences")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ClassSubjectGroup", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.SchoolClass", "Class")
                        .WithMany("SubjectGroups")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.Subject", "Subject")
                        .WithMany("ClassSubjectGroups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.Teacher", "Teacher")
                        .WithMany("ClassSubjectGroups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ScheduledLesson", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.ClassSubjectGroup", "ClassSubjectGroup")
                        .WithMany("ScheduledLessons")
                        .HasForeignKey("ClassSubjectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.Room", "Room")
                        .WithMany("ScheduledLessons")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.Teacher", "Teacher")
                        .WithMany("ScheduledLessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.TimeSlot", "TimeSlot")
                        .WithMany("ScheduledLessons")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSubjectGroup");

                    b.Navigation("Room");

                    b.Navigation("Teacher");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.SchoolClass", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.Room", "HomeRoom")
                        .WithMany()
                        .HasForeignKey("HomeRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomeRoom");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Substitution", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.ScheduledLesson", "ScheduledLesson")
                        .WithMany("Substitutions")
                        .HasForeignKey("ScheduledLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.Room", "SubstituteRoom")
                        .WithMany()
                        .HasForeignKey("SubstituteRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolSchedule.Core.Models.Teacher", "SubstituteTeacher")
                        .WithMany()
                        .HasForeignKey("SubstituteTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ScheduledLesson");

                    b.Navigation("SubstituteRoom");

                    b.Navigation("SubstituteTeacher");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.TeacherSubject", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Core.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.TeacherUnavailability", b =>
                {
                    b.HasOne("SchoolSchedule.Core.Models.Teacher", "Teacher")
                        .WithMany("Unavailabilities")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ClassSubjectGroup", b =>
                {
                    b.Navigation("ScheduledLessons");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Room", b =>
                {
                    b.Navigation("ScheduledLessons");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.ScheduledLesson", b =>
                {
                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.SchoolClass", b =>
                {
                    b.Navigation("SubjectGroups");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjectGroups");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.Teacher", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("ClassSubjectGroups");

                    b.Navigation("ScheduledLessons");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("Unavailabilities");
                });

            modelBuilder.Entity("SchoolSchedule.Core.Models.TimeSlot", b =>
                {
                    b.Navigation("ScheduledLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
